thiagonunes11/testRigorPlayground

main.html
pages/scrollDown.html

You need to scroll down to find all desired information.

Creates the scroll down demo

---

pages/similarPages.html
pages/similarPages/secondVersion.html

Include the author's name in the result message.

Modify Similar Pages demo

---

index.html
pages/browserPrompt.html
pages/browserPromptOnLoad.html
scripts/browserPrompts.js

The first page contains a browser prompt on button click. The second has the same browser prompt on window load. In both cases the user is required to enter a value before proceeding to the page.

Browser prompt

---

index.html
pages/browserPrompt.html
pages/connectTheDots.html
scripts/connectTheDots.js

The first page contains a triangle with dots 1,2,3 and a button that shows the second figure, a hexagon with connectable dots from 1 to 6.

Connect The Dots: Canvas page

---

index.html
pages/qrCode.html

Page where the user can create a QR Code based on a given text input. This can be used to validate QR Code scanning functionality.

Add QR Code page

---

index.html
pages/rightClick.html
scripts/rightClick.js

The demo is a bit simple, just checks if a button was right clicked and changes the text inside it.
If any more features are needed on this demo, let me know. If it's not needed, I believe it's good to merge.

Right click

---

package-lock.json
package.json
src/App.js
src/components/Footer.js
src/components/Header.js

Add footer and header

---

pages/emailValidation.html

allow domains that contain a dash

---

pages/emailValidation.html

allow emails of up to 60 characters

---

src/App.js
src/components/Footer.js
src/components/Header.js
src/components/Sidebar.js

It still needs some fixes, the background color is not taking all the sidebar for some reason.

Improves the main page

---

src/App.js
src/pages/checkbox.js

Add the Checkbox react page

---

src/App.js
src/pages/radioButtons.js

and added a small new functionality, namely the cancel button

implemented the radion buttons react page

---

pages/fileUpload.html
scripts/fileUpload.js

Add file types to the file upload page

---

pages/fileUpload.html
scripts/fileUpload.js

Now it'll give you an error if the file extension is different from the selected one. Also added audio files support.

added more file types and also a file type check

---

index.html
pages/divTable.html

Add div table

---

index.html
scripts/dragItem.js
scripts/index.js

Fix on dragItem.js to work on mobile
Fix on index.html and index.js to have individual descriptive button name for each demo

Hotfix 03 13 2025

---

index.html
src/pages/dragItem.jsx
src/styles/dragItem.css

Reverts thiagonunes11/testRigorPlayground#69
Causes some problems when not on mobile

Revert "Hotfix 03 20 25"

---

src/pages/deleteElements.jsx
src/pages/fileDownload.jsx

The Pull Request #78 created a couple of import duplicates that broke the main page. This PR resolves this.

Fixes duplicate imports from some demos

---

src/components/SearchResult.jsx
src/pages/rightClick.jsx
src/pages/scrollDown.jsx
src/pages/shadowDom.jsx
src/pages/shoppingCart.jsx
src/pages/similarPages.jsx
src/pages/similarPages/secondVersion.jsx
src/pages/svgElements.jsx
src/pages/tableRelativePosition.jsx
src/styles/homePage.css
src/styles/svgElements.css

Updates the following demos to use the new css and formatting:
* Relative Position Table;
* Right Click;
* Scroll Down;
* Shadow DOM;
* Shopping Cart;
* Similar Pages;
* SVG Elements.

Fixes multiple demos to use the css and formatting

---

src/pages/dragItem.jsx
src/pages/dropdowns.jsx
src/pages/dynamicLoginText.jsx
src/pages/waitMessage.jsx
src/styles/dragItem.css
src/styles/dropdowns.css

fixed dark/light mode -> dragItem and Dropdown +  made the fields password and login editable fields

Fixed Drag Item/Dropdrown/Dynamic Login

---

src/App.jsx
src/pages/waitImage.jsx
src/store/demos.jsx

Migrates the demo Wait for the Image to react

---

src/pages/pseudo.jsx

Pseudo elements
